=== wro4j/wro4j/wro4j-core/src/main/resources/ro/isdc/wro/wro.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.isdc.ro/wro" xmlns="http://www.isdc.ro/wro"
	elementFormDefault="qualified">

	<xsd:element name="groups" type="Groups" />

	<xsd:complexType name="Groups">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="import" type="xsd:string"/>
			<xsd:element name="group" type="Group" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="Group">
		<xsd:choice  minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="css">
				<xsd:complexType mixed="true">
					<xsd:attribute name="minimize" type="xsd:boolean"
						use="optional" default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="js">
				<xsd:complexType mixed="true">
					<xsd:attribute name="minimize" type="xsd:boolean"
						use="optional" default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="group-ref" type="xsd:string" />
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="abstract" type="xsd:boolean"
            use="optional" default="false" />
	</xsd:complexType>

</xsd:schema>

=== wro4j/wro4j/wro4j-examples/src/main/webapp/WEB-INF/wro.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.isdc.ro/wro wro.xsd">

  <group name="dynamicResource">
    <js>/resource/redirect.js</js>
    <!-- <js>/resource/dynamic.js</js> -->
  </group>
  
  <group name="all">
    <group-ref>jquery</group-ref>
    <group-ref>twitterBar</group-ref>
    <group-ref>dynamicResource</group-ref>
    <group-ref>WEBINF-css</group-ref>
    <group-ref>uniform</group-ref>
    <group-ref>dwr</group-ref>
	</group>

  <group name="problem">
    <js>/static/js/problem.js</js>
  </group>
  
  <group name="invalid">
    <js>/invalid/resource.js</js>
  </group>
  
  <group name="twitterBar">
    <js>http://widgets.twimg.com/j/2/widget.js</js>
  </group>
  
  <group name="WEBINF-css">
    <js>/external/resource.js</js>  
    <css>/WEB-INF/css/webinf.css</css>
  </group>
  
  <group name="wildcard">
    <css>/static/**.css</css>
    <js>/static/js/*.js</js>
    <css>/WEB-INF/css/*.css</css>
    <css>classpath:ro/isdc/wro/resources/**.cs?</css>
  </group>

  <group name="uniform">
    <css>/static/css/webapp.css</css>
    <css>/static/css/css1.css</css>
    <css>/static/css/css2.css</css>
    <css>/static/css/NOTEXIST.css</css>
    <css>classpath:ro/isdc/wro/resources/*.css</css>
  </group>
	
	<group name="otherGroup">
		<css>/static/css/variablesSupport.css</css>
	</group>
  
  <group name="wicket">
    <js>classpath:org/apache/wicket/ajax/wicket-ajax-debug.js</js>
  </group>
  
  <group name="dwr">
    <js>/dwr/engine.js</js>
    <js>/dwr/interface/DWRFacade.js</js>
  </group>
  
  <group name="chineseEncoding">
    <js>http://wro4j.googlecode.com/svn/wiki/static/encoding/chinese.js</js>
     <!--<js>http://search.trade2cn.com/js/vsp.com/rct_keyword.js</js> -->
  </group>

  <group name="JSGroup">
    <js>/dwr/engine.js</js>
    <js>/dwr/interface/DWRFacade.js</js>
  </group>

  <group name="justJquery">
    <js>/static/js/jquery-1.4.3.js</js>
  </group>

  <group name="jquery">
    <js>http://code.jquery.com/jquery-1.4.4.min.js</js>
    <group-ref>jquery-mobile</group-ref>
    <!--
    <js>/static/js/jquery.livequery.js</js>
    <js>/static/js/jquery-validate.js</js>
    <js>/static/js/jquery-ui-all.js</js>
     -->
  </group>
  
  <group name="jquery-mobile">
    <css>http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.css</css>
    <js> http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.js</js>
  </group>
  
  <group name="syntaxHighlighter">
    <js>/static/module/syntaxHighlighter/scripts/shCore.js</js>
    <js>/static/module/syntaxHighlighter/scripts/bootstrap.js</js>
    <js>/static/module/syntaxHighlighter/scripts/*.js</js>
    <!--
    
    <js>/static/module/syntaxHighlighter/scripts/shCore.js</js>
    <js>/static/module/syntaxHighlighter/scripts/shBrushJScript.js</js>
    <js>/static/module/syntaxHighlighter/scripts/shBrushAppleScript.js</js>  
    -->
	  <css>/static/module/syntaxHighlighter/styles/shCoreDefault.css</css>
  </group>
  
  
  
  <group name="classpath">
    <css>classpath:com/mysite/myapplication/web/resources/*.css</css>
    <js>classpath:com/mysite/myapplication/web/resources/*.js</js>
	</group>
  
</groups>
